version: '3.4'

services:
  scalingapi:
    image: ${DOCKER_REGISTRY-}scalingapi
    ports:
        - 8080:8080
    build:
      context: .
      dockerfile: ScalingApi/Dockerfile

  workernode:
    image: ${DOCKER_REGISTRY-}workernode
    build:
      context: .
      dockerfile: WorkerNode/Dockerfile


